### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by albertodainotti** [InetIntel/grip-ui#10]
Add acknowledgements to https://grip.inetintel.cc.gatech.edu/ack. 
At least GCA, Amazon, and Google

**Comment by albertodainotti** [comment]
- The MANRS project at the Global Cyber Alliance https://globalcyberalliance.org
- Google Research http://research.google
- Amazon https://www.amazon.science

**Comment by Tejas988** [comment]
For adding acknowledgment to the MANRS project, prof has suggested adding two hyperlinks (manrs.org on clicking the logo and globalcyberalliance.org for "Global Cyber Alliance" in the description.

But as per the current code structure, we can't add multiple hyperlinks for a particular acknowledgment Card component. Any other way we could handle this or do I have to modify the component for this specific requirement? @salcock

**Comment by salcock** [comment]
Yes, currently the `link` anchor applies to the entire card so you'll need to re-define the `render()` method to apply one link (perhaps defined as `imagelink` in the `orgs` list) to the image div and another link to the desc div.

If `imagelink` is not defined, then fall back to using the regular link instead for the image div so you don't have to duplicate the links for all of the existing orgs ;)

**Comment by albertodainotti** [comment]
Hi all. We care more about timing than anything else. We can use just the MANRS link for that card for now.
